name: Awesome CI - Esdiel

on:
  pull_request:
    paths:
      - 'serverless-data-lake/**'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd serverless-data-lake
          make install
      - name: Format and lint Python code
        run: |
          cd serverless-data-lake && make format && make lint
